# Generated by Django 4.0.1 on 2022-01-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshippreferencemodel',
            name='end_data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='internshippreferencemodel',
            name='start_data',
            field=models.DateTimeField(),
        ),
    ]
