# Generated by Django 4.0.1 on 2022-01-29 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_api', '0002_alter_internshippreferencemodel_end_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=100)),
                ('duration_start', models.DateTimeField()),
                ('duration_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('tools_id', models.IntegerField()),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('country_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('compensation', models.IntegerField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_api.internshippreferencemodel')),
            ],
        ),
    ]
